### PR TITLE
Upgrade database connector to version 8.6

### PR DESCRIPTION
**Pull request by Borzoo**

### CODE REVIEW

**Comment by basdebakker** [comment]
Why the Mockito downgrade?

**Comment by zubivan** [comment]
@Borzoo do you think we can split it into 2 PRs? One to convert to 8 (basically one that takes care of conversion) and another one that converts to 8.6 and introduces typed template argument.

**Comment by Borzoo** [comment]
> Why change Mockito version?
The tests were failing because of a null reference error somewhere in mockito library after upgrading to 8.6. 
> Why downgrade Mockito?
Seemed like the safest choice because it didn't have any dependencies, and it worked. In hindsight I think upgrading it would have been the better choice.

**Comment by zubivan** [comment]
LGTM from LC side.

**Pull request merged**
